import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html data-theme="light" lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} bg-base-300 h-screen w-screen antialiased flex flex-col`}
			>
				<main className="flex-1 ">{children}</main>
				<footer>
					<p className="text-center text-sm text-gray-600 dark:text-gray-400 pb-5 ">
						© {new Date().getFullYear()} roomvibe. All rights reserved.
					</p>
				</footer>
			</body>
		</html>
	);
}
