import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html data-theme="light" lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} bg-base-300 h-screen w-screen antialiased flex flex-col`}
			>
				<main className="flex-1 p-5 flex flex-col items-center">
					<h1 className="self-start text-2xl md:text-4xl font-extrabold bg-gradient-to-r from-blue-400 via-fuchsia-500 to-amber-500 bg-clip-text text-transparent mb-8">
						roomvibe
					</h1>

					<div className=" sm:w-3/4 md:w-2/3 lg:w-3/5 mx-auto">{children}</div>
				</main>
				<footer>
					<p className="text-center text-sm text-gray-600 dark:text-gray-400 pb-5 ">
						© {new Date().getFullYear()} roomvibe. All rights reserved.
					</p>
				</footer>
			</body>
		</html>
	);
}
